package com.namoadigital.prj001.database.scripts.multi.ticket

const val TK_TICKET_FORM_CREATE_SCRIPT =
    """ CREATE TABLE IF NOT EXISTS [tk_ticket_form] 
    ( 
        [customer_code] int not null,                                                                         
        [ticket_prefix] int not null, 
        [ticket_code] int not null, 
        [ticket_seq] int not null, 
        [ticket_seq_tmp] int not null default 0, 
        [step_code] int not null, 
        [form_status] text not null collate nocase, 
        [custom_form_type] int not null, 
        [custom_form_code] int not null, 
        [custom_form_version] int not null, 
        [custom_form_version_partition] int, 
        [custom_form_desc] text not null collate nocase, 
        [custom_form_data] int, 
        [score_status] text collate nocase, 
        [score_perc] text collate nocase, 
        [nc] int not null default 0, 
        [is_so] int not null default 0, 
        [custom_form_data_tmp] int default null, 
        [pdf_code] int, 
        [pdf_name] text collate nocase, 
        [pdf_url] text collate nocase, 
        [pdf_url_local] text collate nocase, 
        [custom_form_data_partition] int, 
        [order_type_code] int,
        [order_type_id] text collate nocase,
        [order_type_desc] text collate nocase, 
        [process_type] text collate nocase, 
        [display_option] text collate nocase,
        [process_vg] text collate nocase,
        [item_check_group_code] int,
        [measure_tp_code] int, 
        [measure_tp_desc] text collate nocase, 
        [measure_value] real, 
        [measure_cycle_value] real, 
        [value_sufix] text collate nocase, 
        [start_date] text collate nocase, 
        [partition_min_date] text collate nocase, 
        CONSTRAINT [pk_tk_ticket_form] 
        PRIMARY KEY([customer_code], [ticket_prefix], [ticket_code], [step_code], [ticket_seq_tmp])
    );
    """

const val TK_TICKET_CREATE_SCRIPT = """
    CREATE TABLE IF NOT EXISTS[tk_ticket]
    (
        [customer_code]int NOT NULL,                                                                    
        [ticket_prefix]int NOT NULL,                                                                    
        [ticket_code]int NOT NULL,                                                                      
        [scn]int NOT NULL,                                                                              
        [user_level_min]int NOT NULL default 0,                                                         
        [ticket_id]text NOT NULL COLLATE nocase,                                                        
        [ticket_edi_id]text COLLATE nocase,                                                        
        [tag_operational_code]int not null,                                                             
        [tag_operational_id]text not null collate nocase,                                               
        [tag_operational_desc]text not null collate nocase,                                           
        [type_code]int NOT NULL,                                                                        
        [type_id]text NOT NULL COLLATE nocase,                                                          
        [type_desc]text NOT NULL COLLATE nocase,                                                        
        [app_personal_data]int not null default 0,                                                      
        [type_path]text COLLATE nocase,                                                                 
        [open_comments]text COLLATE nocase,                                                             
        [open_photo]text COLLATE nocase,                                                                
        [open_photo_local]text COLLATE nocase,                                                          
        [open_name]text COLLATE nocase,                                                                
        [open_email]text COLLATE nocase,                                                                
        [open_phone]text COLLATE nocase,                                                                
        [open_date]text NOT NULL COLLATE nocase,                                                        
        [open_user]int NOT NULL,                                                                        
        [open_user_name]text NOT NULL COLLATE nocase,                                                   
        [internal_comments]text COLLATE nocase,                                                         
        [open_site_code]int NOT NULL,                                                                   
        [open_site_id]text NOT NULL COLLATE nocase,                                                     
        [open_site_desc]text NOT NULL COLLATE nocase,                                                   
        [open_zone_code]int,                                                                              
        [open_zone_id]text COLLATE nocase,                                                              
        [open_zone_desc]text COLLATE nocase,                                                            
        [open_operation_code]int NOT NULL,                                                              
        [open_operation_id]text NOT NULL COLLATE nocase,                                                
        [open_operation_desc]text NOT NULL COLLATE nocase,                                             
        [open_product_code]int NOT NULL,                                                                
        [open_product_id]text NOT NULL COLLATE nocase,                                                  
        [open_product_desc]text NOT NULL COLLATE nocase,                                                
        [open_serial_code]int NOT NULL,                                                                 
        [open_serial_id]text NOT NULL COLLATE nocase,                                                   
        [start_date]text COLLATE nocase,                                                                
        [forecast_date]text COLLATE nocase,                                                             
        [forecast_time]text COLLATE nocase,                                                             
        [ticket_status]text NOT NULL COLLATE nocase,                                                    
        [close_date]text COLLATE nocase,                                                                
        [close_user]int,                                                                                
        [close_user_name]text COLLATE nocase,                                                           
        [duration_minutes]int,                                                                          
        [barcode_code]int,                                                                              
        [pc_code]int,                                                                                   
        [pc_id]text COLLATE NOCASE,                                                                     
        [pc_desc]text COLLATE NOCASE,                                                                   
        [main_user]int,                                                                                 
        [main_user_nick]text COLLATE NOCASE,                                                            
        [main_user_name]text COLLATE NOCASE,                                                            
        [pipeline_code]int,                                                                             
        [pipeline_id]text COLLATE NOCASE,                                                               
        [pipeline_desc]text COLLATE NOCASE,                                                             
        [current_step_order]int,                                                                        
        [approval_rejected]int not null default 0,                                                      
        [origin_type]text not null COLLATE NOCASE,                                                      
        [origin_desc]text not null COLLATE NOCASE,                                                      
        [valid_structure_step]int not null default 0,                                                   
        [inventory_control]int not null default 0,                                                      
        [user_focus]int not null default 0,                                                             
        [has_item_check]int not null default 0,                                                         
        [allow_step_approval]int not null default 0,                                                    
        [sync_required]int not null default 0,                                                          
        [update_required]int not null default 0,                                                        
        [update_required_product]int not null default 0,                                                
        [update_required_status]int not null default 0,                                                 
        [token]text,                                                                                    
        [schedule_prefix]int,                                                                           
        [schedule_code]int,                                                                             
        [schedule_exec]int,                                                                             
        [client_code]number,                                                                            
        [client_id]text COLLATE NOCASE,                                                                 
        [client_name]text COLLATE NOCASE,                                                               
        [address_country_id]text COLLATE NOCASE,                                                           
        [address_country]text COLLATE NOCASE,                                                           
        [address_state]text COLLATE NOCASE,                                                             
        [address_city]text COLLATE NOCASE,                                                              
        [address_district]text COLLATE NOCASE,                                                          
        [address_street]text COLLATE NOCASE,                                                            
        [address_num]text COLLATE NOCASE,                                                               
        [address_complement]text COLLATE NOCASE,                                                        
        [address_zipcode]text COLLATE NOCASE,                                                           
        [address_lat] text COLLATE NOCASE,                                                               
        [address_lng] text COLLATE NOCASE,                                                               
        [address_plus_code]text COLLATE NOCASE,                                                               
        [contact_name] text COLLATE NOCASE,                                                               
        [contact_phone] text COLLATE NOCASE,                                                               
        [contract_code]number,                                                                          
        [contract_id]text COLLATE NOCASE,                                                               
        [contract_desc]text COLLATE NOCASE,                                                             
        [fcm_scn]int not null default 0,                                                                
        [justify_group_code]int,                                                                        
        [justify_item_code]int,                                                                         
        [justify_item_id]text,                                                                          
        [justify_item_desc]text,                                                                        
        [not_executed_comments]text COLLATE NOCASE,                                                     
        [not_executed_photo_name]text COLLATE NOCASE,                                                   
        [not_executed_photo_url]text COLLATE NOCASE,                                                    
        [not_executed_photo]int,                                                                        
        [not_executed_date]text COLLATE NOCASE,                                                         
        [class_code]int,                                                                                
        [class_id]text collate nocase,                                                                  
        [class_color]text collate nocase,                                                               
        [class_available]int,                                                                           
        [kanban]int not null default 0,                                                                 
        [kanban_stage] text,                                                                         
        [kanban_date] text,                                                             
        [kanban_custom_form_type] int,                                                  
        [kanban_custom_form_code] int,
        [kanban_open_continue] int,
        [able_to_done] int not null default 0, 
        [preventive] int, 
        [is_priority] int, 
        [has_open_so_partition]int not null default 0,                                               
        [has_address]int not null default 0,
        [open_serial_stopped] text COLLATE NOCASE,
        [open_desired_date] text COLLATE NOCASE,
        [is_serial_stopped] int not null default 0,
        [stopped_date] text,
        [desired_date] text,
        [is_tmp] int not null default 0,
        [sync_big_file] int not null default 0,
        CONSTRAINT[pk_tk_ticket]
        PRIMARY KEY([customer_code], [ticket_prefix], [ticket_code]));
"""

const val TK_TICKET_CACHE_CREATE_SCRIPT = """
    CREATE TABLE IF NOT EXISTS [tk_ticket_cache] 
    (
        [customer_code] int not null,
        [ticket_prefix] int not null,
        [ticket_code] int not null,
        [scn] int not null,
        [user_level_min] int not null,
        [ticket_id] text not null collate nocase,
        [ticket_edi_id] text COLLATE nocase,
        [tag_operational_code] int not null,
        [tag_operational_id] text not null collate nocase,
        [tag_operational_desc] text not null collate nocase,
        [type_code] int not null,
        [type_id] text not null collate nocase,
        [type_desc] text not null collate nocase,
        [user_focus] int not null,
        [main_user] int,
        [order_by] int not null,
        [client_code] int ,
        [client_id] text COLLATE nocase,
        [client_name] text COLLATE nocase,
        [contract_code] int ,
        [contract_id] text COLLATE nocase,
        [contract_desc] text COLLATE nocase,
        [open_site_code] int not null,
        [open_site_desc] text not null collate nocase,
        [open_zone_code]int,
        [open_zone_desc]text COLLATE nocase,
        [open_operation_code] int NOT NULL,
        [open_operation_desc] text NOT NULL COLLATE nocase,
        [open_product_code] int not null,
        [open_product_desc] text not null collate nocase,
        [open_serial_id] text not null collate nocase,
        [current_step_order] int ,
        [ticket_status] text not null collate nocase,
        [origin_type] text not null collate nocase,
        [origin_desc] text not null collate nocase,
        [internal_comments] text collate nocase,
        [step_desc] text collate nocase,
        [forecast_start] text collate nocase,
        [forecast_end] text collate nocase,
        [step_count] int not null,
        [step_order_seq] int,
        [class_code] int,
        [class_id] text collate nocase,
        [class_color] text collate nocase,
        [class_available] int,
        [kanban]int not null default 0,
        [kanban_stage] text,
        [able_to_done] int not null default 0,
        [preventive] int,
        [is_priority] int,
        [address] int,
        [automatic_ticket_download] int not null default 0,
        [sync_big_file] int not null default 0,
        CONSTRAINT [pk_tk_ticket_cache]
        PRIMARY KEY (customer_code,ticket_prefix,ticket_code));
"""
const val TK_TICKET_CTRL_CREATE_SCRIPT = """
    CREATE TABLE IF NOT EXISTS [tk_ticket_ctrl] 
    (
        [customer_code] int NOT NULL, 
        [ticket_prefix] int NOT NULL, 
        [ticket_code] int NOT NULL, 
        [ticket_seq] int NOT NULL, 
        [ticket_seq_tmp] int NOT NULL default 0, 
        [step_code] int not null, 
        [step_order] int default 0, 
        [obj_planned] int not null default 0, 
        [ctrl_type] text NOT NULL COLLATE nocase, 
        [product_code] int , 
        [product_id] text COLLATE nocase, 
        [product_desc] text COLLATE nocase, 
        [serial_code] int, 
        [serial_id] text COLLATE nocase, 
        [has_item_check] int, 
        [ctrl_start_date] text COLLATE nocase, 
        [ctrl_start_user] int , 
        [ctrl_start_user_name] text COLLATE nocase,
        [ctrl_end_date] text COLLATE nocase,
        [ctrl_end_user] int, 
        [ctrl_end_user_name] text COLLATE nocase, 
        [ctrl_status] text NOT NULL COLLATE nocase, 
        [partner_code] int, 
        [partner_id] text COLLATE nocase, 
        [partner_desc] text COLLATE nocase , 
        [update_required] int not null default 0, 
        [from_to_notify] int not null default 0 , 
        [trip_prefix] int, 
        [trip_code] int, 
        [destination_seq] int,
        CONSTRAINT [pk_tk_ticket_ctrl] 
        PRIMARY KEY( 
            [customer_code] , 
            [ticket_prefix] , 
            [ticket_code] , 
            [step_code] ,
            [ticket_seq_tmp]
        )
    );
"""