package com.namoadigital.prj001.database.scripts.multi

const val GE_OS_CREATE_SCRIPT =
    """
    CREATE TABLE IF NOT EXISTS [ge_os](
        [customer_code]int not null, 
        [custom_form_type]int not null, 
        [custom_form_code]int not null, 
        [custom_form_version]int not null, 
        [custom_form_data]int not null, 
        [order_type_code] int not null collate nocase, 
        [order_type_id] text not null collate nocase,
        [order_type_desc] text not null collate nocase, 
        [process_type] text not null collate nocase,
        [display_option] text not null collate nocase,
        [item_check_group_code] int,
        [backup_product_code] int, 
        [backup_product_id] text collate nocase, 
        [backup_product_desc] text collate nocase, 
        [backup_serial_code] int, 
        [backup_serial_id] text collate nocase,
        [measure_tp_code] int , 
        [measure_tp_id] text collate nocase, 
        [measure_tp_desc] text collate nocase,
        [measure_value] real ,
        [measure_cycle_value] real, 
        [value_sufix] text collate nocase, 
        [restriction_decimal] int, 
        [value_cycle_size] real, 
        [cycle_tolerance] int, 
        [date_start] text, 
        [date_end] text , 
        [last_measure_value] real,
        [last_measure_date] text collate nocase, 
        [last_cycle_value] real, 
        [so_edit_start_end] int not null DEFAULT 0, 
        [so_order_type_code_default] int, 
        [so_allow_change_order_type] int not null DEFAULT 0,
        [so_allow_backup]  int not null DEFAULT 0, 
        [device_tp_code_main] int, 
        [initial_is_serial_stopped] int,
        [initial_stopped_date] text collate nocase,
        [initial_unavailability_reason] text collate nocase,
        [final_is_serial_stopped] int,                                   
        [final_unavailability_reason] text collate nocase,
        [allow_form_in_the_past] int not null DEFAULT 0,
        constraint[pk_ge_os] primary key([customer_code], [custom_form_type], [custom_form_code], [custom_form_version], [custom_form_data]));
"""