package com.namoadigital.prj001.database.scripts.multi

const val GE_OS_DEVICE_ITEM_CREATE_TABLE =
    """
        CREATE TABLE IF NOT EXISTS [ge_os_device_item]( 
            [customer_code] int not null,
            [custom_form_type]int not null, 
            [custom_form_code]int not null, 
            [custom_form_version]int not null, 
            [custom_form_data]int not null, 
            [product_code] int not null, 
            [serial_code] int not null, 
            [device_tp_code] int not null, 
            [item_check_code] int not null, 
            [item_check_seq] int not null, 
            [item_check_id] text not null collate nocase, 
            [item_check_desc] text not null collate nocase,
            [item_check_desc_alt_vg] text collate nocase,
            [item_check_group_code] int, 
            [apply_material] text not null collate nocase, 
            [verification_instruction] text collate nocase, 
            [require_justify_problem] int not null default 0, 
            [critical_item] int not null default 0, 
            [change_adjust] int not null default 0, 
            [order_seq] int not null, 
            [structure] int not null, 
            [already_ok_hide] int not null default 0, 
            [require_photo_fixed] int not null default 0, 
            [require_photo_alert] int not null default 0, 
            [require_photo_already_ok] int not null default 0, 
            [require_photo_not_verified] int not null default 0, 
            [vg_code] int,
            [manual_desc] text collate nocase, 
            [next_cycle_measure] real, 
            [next_cycle_measure_date] text collate nocase, 
            [next_cycle_limit_date] text collate nocase,  
            [value_sufix] text collate nocase, 
            [restriction_decimal] int, 
            [item_check_status] text not null collate nocase, 
            [target_date] text collate nocase, 
            [exec_type] text collate nocase, 
            [exec_date] text collate nocase, 
            [exec_comment] text collate nocase, 
            [exec_photo1] text collate nocase, 
            [exec_photo2] text collate nocase, 
            [exec_photo3] text collate nocase, 
            [exec_photo4] text collate nocase, 
            [status_answer] text collate nocase, 
            [has_expired_cycle] int not null, 
            [hide_days_in_alert] int not null default 0, 
            [partitioned_execution] int not null default 0, 
            [ticket_prefix] int, 
            [ticket_code] int,
            [vg_action] int not null default 0, 
            [is_visible] int not null default 0, 
            [color_item] text not null collate nocase, 
            [status_modification_type] text collate nocase, 
            [automatic_selection_state] text collate nocase, 
            
            constraint [pk_ge_os_device_item] primary key
            (
                customer_code,
                custom_form_type,
                custom_form_code,
                custom_form_version,
                custom_form_data,
                product_code,
                serial_code,
                device_tp_code,
                item_check_code,
                item_check_seq
            )
        );"""