package com.namoadigital.prj001.database.scripts.multi

import com.namoadigital.prj001.dao.SM_SODao

const val SM_SOS_CREATE_SCRIPT =
    """
    CREATE TABLE IF NOT EXISTS [sm_sos](
        [customer_code] int NOT NULL,
        [so_prefix] int NOT NULL,
        [so_code] int NOT NULL,
        [so_id] text NOT NULL,
        [so_scn] int NOT NULL,
        [so_desc] text,
        [product_code] int NOT NULL,
        [product_id] text NOT NULL COLLATE nocase,
        [product_desc] text NOT NULL COLLATE nocase,
        [serial_code] int NOT NULL,
        [serial_id] text NOT NULL COLLATE nocase,
        [category_price_code] int NOT NULL,
        [category_price_id] text NOT NULL,
        [category_price_desc] text NOT NULL,
        [segment_code] int NOT NULL,
        [segment_id] text NOT NULL,
        [segment_desc] text NOT NULL,
        [site_code] int NOT NULL,
        [site_id] text NOT NULL,
        [site_desc] text NOT NULL,
        [operation_code] int NOT NULL,
        [operation_id] text NOT NULL,
        [operation_desc] text NOT NULL,
        [contract_code] int NOT NULL,
        [contract_desc] text NOT NULL,
        [contract_po_erp] text,
        [contract_po_client1] text,
        [contract_po_client2] text,
        [contract_po_client3] text,
        [po_code] int NOT NULL,
        [po_id] text NOT NULL COLLATE nocase,
        [po_desc] text DEFAULT '' COLLATE nocase,
        [priority_code] int NOT NULL,
        [priority_desc] text NOT NULL,
        [status] text NOT NULL,
        [quality_approval_user] int,
        [quality_approval_user_nick] text,
        [quality_approval_date] text,
        [comments] text,
        [so_father_prefix] int,
        [so_father_code] int,
        [deadline] text,
        [origin] text NOT NULL,
        [client_type] text NOT NULL,
        [client_user] int,
        [client_code] int,
        [client_id] text,
        [client_name] text,
        [client_email] text,
        [client_phone] text,
        [client_approval_image] int,
        [client_approval_image_name] text,
        [client_approval_image_url] text,
        [client_approval_image_url_local] text,
        [client_approval_date] text,
        [client_approval_user] int,
        [client_approval_user_nick] text,
        [client_approval_type_sig] text,
        [client_so_id] text,
        [origin_change] text NOT NULL,
        [started_flag] int NOT NULL,
        [edit_origin] text,
        [edit_user] int,
        [edit_user_nick] text,
        [total_qty_service] int NOT NULL,
        [total_price] real NOT NULL,
        [add_inf1] text,
        [add_inf1_tracking] int,
        [add_inf2] text,
        [add_inf2_tracking] int,
        [add_inf3] text,
        [add_inf3_tracking] int,
        [add_inf4] text,
        [add_inf4_tracking] int,
        [add_inf5] text,
        [add_inf5_tracking] text,
        [add_inf6] text,
        [add_inf6_tracking] text,
        [billing_add_inf1] text,
        [billing_add_inf1_tracking] text,
        [billing_add_inf2] text,
        [billing_add_inf2_tracking] text,
        [billing_add_inf3] text,
        [billing_add_inf3_tracking] text,
        [serial_add_inf1] text,
        [serial_add_inf2] text,
        [serial_add_inf3] text,
        [approve_budget] int NOT NULL DEFAULT 0,
        [approve_client] int NOT NULL DEFAULT 0,
        [update_required] int NOT NULL DEFAULT 0,
        [approval_required] int NOT NULL DEFAULT 0,
        [sync_required] int NOT NULL DEFAULT 0,
        [log_date] text,
        [log_user] int NOT NULL,
        [log_user_nick] text NOT NULL COLLATE nocase,
        [token] text NOT NULL DEFAULT '' COLLATE nocase,
        [product_icon_name] text COLLATE nocase,
        [product_icon_url] text COLLATE nocase,
        [product_icon_url_local] text NOT NULL DEFAULT '' COLLATE nocase,
        [room_member] int NOT NULL DEFAULT 0,
        [room_code] text,
        [site_exec] int NOT NULL,
        [site_exec_id] text NOT NULL COLLATE nocase,
        [site_exec_desc] text NOT NULL COLLATE nocase,
        [create_date] text NOT NULL COLLATE nocase,
        [create_user] int NOT NULL,
        [create_user_nick] text NOT NULL COLLATE nocase,
        [last_approval_budget_date] text COLLATE nocase,
        [last_approval_budget_user] int,
        [last_approval_budget_user_nick] text COLLATE nocase,
        [pipeline_code] int,
        [pipeline_desc] text COLLATE nocase,
        [deadline_manual] int NOT NULL DEFAULT 0,
        [has_client_deadline] int NOT NULL DEFAULT 0,
        [${SM_SODao.RESERVED_USER}] int,
        [${SM_SODao.RESERVED_USER_NAME}] text,
        [${SM_SODao.RESERVED_USER_NICK}] text,
        [${SM_SODao.RESERVED_DATE}] text,
        PRIMARY KEY([customer_code], [so_prefix], [so_code])
    );
    """

const val SM_SO_FILES_CREATE_SCRIPT =
    """
    CREATE TABLE IF NOT EXISTS [sm_so_files](
        [customer_code] int NOT NULL,
        [so_prefix] int NOT NULL,
        [so_code] int NOT NULL,
        [file_code] int NOT NULL,
        [file_name] text NOT NULL,
        [file_url] text NOT NULL,
        [file_url_local] text NOT NULL,
        [file_custom_form_pk] text,
        PRIMARY KEY([customer_code], [so_prefix], [so_code], [file_code])
    );
    """

const val SM_SO_PACKS_CREATE_SCRIPT =
    """
    CREATE TABLE IF NOT EXISTS [sm_so_packs](
        [customer_code] int NOT NULL,
        [so_prefix] int NOT NULL,
        [so_code] int NOT NULL,
        [price_list_code] int NOT NULL,
        [pack_code] int NOT NULL,
        [pack_seq] int NOT NULL,
        [price_list_id] text NOT NULL,
        [price_list_desc] text NOT NULL,
        [pack_id] text NOT NULL,
        [pack_desc] text NOT NULL,
        [status] text NOT NULL,
        [rule] text,
        [billing_type] text NOT NULL,
        [express] int,
        [selection_type] text NOT NULL,
        PRIMARY KEY([customer_code], [so_prefix], [so_code], [price_list_code], [pack_code], [pack_seq])
    );
    """