package com.namoadigital.prj001.ui.act005.trip.fragment.base

object TripTranslate {

    const val CANCEL = "tv_cancel"
    const val SAVE = "tv_save"
    const val SAVE_END_TRIP_BTN = "save_end_trip_btn"
    const val TRIP_SUCCESS_SEND_DATA = "trip_success_send_data"
    const val TRIP_SUCCESS_SEND_USER_DATA = "trip_success_send_user_data"
    //Fleet Dialog
    const val FLEET_DIALOG_ORIGIN_TITLE = "fleet_dialog_origin_title"
    const val FLEET_DIALOG_DESTINATION_TITLE = "fleet_dialog_destination_title"
    const val FLEET_DIALOG_END_TITLE = "fleet_dialog_end_title"
    const val FLEET_DIALOG_END_DESC = "fleet_dialog_end_desc"
    const val FLEET_DIALOG_PLATE = "dialog_fleet_plate"
    const val FLEET_DIALOG_ODOMETER = "fleet_dialog_odometer"
    const val FLEET_DIALOG_PHOTO = "fleet_dialog_photo"
    const val FLEET_EDITTEXT_ERROR = "fleet_edittext_error"
    const val ODOMETER_EDITTEXT_ERROR = "odometer_edittext_error"
    const val FLEET_LOW_ODOMETER_ERROR = "fleet_low_odometer_error"
    const val FLEET_PHOTO_DIALOG_REQUIRED = "fleet_photo_dialog_required"
    const val FLEET_PHOTO_DIALOG_ERROR_DOWNLOAD = "fleet_photo_dialog_error_download"

    //DIALOG ERROR
    const val DIALOG_ERROR_CLOSE_LBL = "dialog_error_btn_close"

    object DialogOrigin{

        const val DIALOG_ORIGIN_TITLE = "dialog_origin_title"
        const val DIALOG_ORIGIN_CREATE_TRIP = "dialog_origin_create_trip"
        const val DIALOG_ORIGIN_DATE_HINT = "dialog_origin_date_hint"
        const val DIALOG_ORIGIN_HOUR_HINT = "dialog_origin_hour_hint"
        const val DIALOG_ORIGIN_STARTING_POINT = "dialog_origin_starting_point"
        const val DIALOG_ORIGIN_SITE_OPTIONS_OPTION = "dialog_origin_site_options_option"
        const val DIALOG_ORIGIN_CURRENT_LOCATION_OPTION = "dialog_origin_current_location_option"
        const val DIALOG_ORIGIN_ERROR_FUTURE_DATE = "dialog_origin_error_future_date"

        const val PROGRESS_ORIGIN_TRIP_SET_TTL = "progress_origin_trip_set_ttl"
        const val PROGRESS_ORIGIN_TRIP_SET_MSG = "progress_origin_trip_set_msg"

        const val DIALOG_ORIGIN_ERROR_SAVE_TTL = "dialog_origin_error_save_ttl"
        const val DIALOG_ORIGIN_ERROR_SAVE_MSG = "dialog_origin_error_save_msg"
    }
    //
    const val PROGRESS_TRIP_ERROR_SYNC_APP_TTL = "progress_trip_error_sync_app_ttl"
    const val PROGRESS_TRIP_ERROR_SYNC_APP_MSG = "progress_trip_error_sync_app_msg"
    const val PROGRESS_TRIP_DESTINATION_CHANGE_TTL = "progress_trip_destination_change_ttl"
    const val PROGRESS_TRIP_DESTINATION_CHANGE_MSG = "progress_trip_destination_change_msg"
    const val ALERT_TRIP_DESTINATION_DELETE_TTL = "alert_trip_destination_delete_ttl"
    const val ALERT_TRIP_DESTINATION_DELETE_MSG = "alert_trip_destination_delete_msg"
    const val PROGRESS_CREATE_NEW_TRIP_TTL = "progress_create_new_trip_ttl"
    const val PROGRESS_CREATE_NEW_TRIP_MSG = "progress_create_new_trip_msg"
    const val PROGRESS_CREATE_NEW_TRIP_GET_LOCATION_MSG = "progress_create_new_trip_get_location_msg"
    const val PROGRESS_FLEET_TRIP_SEND_TTL = "progress_fleet_trip_send_ttl"
    const val PROGRESS_FLEET_TRIP_SEND_MSG = "progress_fleet_trip_send_msg"
    const val PROGRESS_ORIGIN_TRIP_SEND_TTL = "progress_origin_trip_send_ttl"
    const val PROGRESS_ORIGIN_TRIP_SEND_MSG = "progress_origin_trip_send_msg"
    const val PROGRESS_ABORT_PENDING_TTL = "progress_abort_pending_ttl"
    const val PROGRESS_ABORT_PENDING_MSG = "progress_abort_pending_msg"
    const val PROGRESS_TRIP_START_TTL = "progress_trip_start_ttl"
    const val PROGRESS_TRIP_START_MSG = "progress_trip_start_msg"
    const val PROGRESS_TRIP_TRANSFER_TTL = "progress_trip_transfer_ttl"
    const val PROGRESS_TRIP_TRANSFER_MSG = "progress_trip_transfer_msg"
    const val PROGRESS_TRIP_WAITING_DESTINATION_TTL = "progress_trip_waiting_destination_ttl"
    const val PROGRESS_TRIP_WAITING_DESTINATION_MSG = "progress_trip_waiting_destination_msg"
    const val PROGRESS_TRIP_END_TTL = "progress_trip_end_ttl"
    const val PROGRESS_TRIP_END_MSG = "progress_trip_end_msg"
    const val PROGRESS_TRIP_OVER_NIGHT_TTL = "progress_trip_over_night_ttl"
    const val PROGRESS_TRIP_OVER_NIGHT_MSG = "progress_trip_over_night_msg"
    const val PROGRESS_TRIP_DESTINATION_EDIT_TLL = "progress_trip_destination_edit_tll"
    const val PROGRESS_TRIP_DESTINATION_EDIT_MSG = "progress_trip_destination_edit_msg"
    const val ALERT_NEW_TRIP_LATLON_ERROR_TTL = "alert_new_trip_latlon_error_ttl"
    const val ALERT_NEW_TRIP_LATLON_ERROR_MSG = "alert_new_trip_latlon_error_msg"
    const val ALERT_NEW_TRIP_MSG = "alert_new_trip_msg"
    const val ALERT_NEW_TRIP_CREATE_BTN = "alert_new_trip_create_btn"
    const val ALERT_NEW_TRIP_CANCEL_BTN = "alert_new_trip_cancel_btn"
    const val BTN_NEW_TRIP = "btn_new_trip"
    const val PLACEHOLDER_TRIP_TTL_LBL = "placeholder_trip_ttl_lbl"
    const val PLACEHOLDER_TRIP_SUB_TTL_LBL = "placeholder_trip_sub_ttl_lbl"
    const val TRIP_LBL = "trip_lbl"
    const val TRIP_START_LBL = "trip_start_lbl"
    const val TRIP_CANCEL_LBL = "trip_cancel_lbl"
    const val TRIP_CREATE_AT_LBL = "trip_create_at_lbl"
    const val TRIP_ORIGIN_POINT_LBL = "trip_origin_point_lbl"
    const val TRIP_ORIGIN_GPS = "trip_origin_gps"
    const val TRIP_FLEET_PLATE_LBL = "trip_fleet_plate_lbl"
    const val TRIP_FLEET_KILOMETERS_LBL = "trip_fleet_kilometers_lbl"
    const val ALERT_TRIP_START_ERROR_TTL = "trip_fleet_kilometers_lbl"
    const val ALERT_TRIP_START_ERROR_MSG = "alert_trip_start_fleet_error_msg"
    const val TRIP_REPORT_BTN = "trip_report_btn"
    const val TRIP_SELECT_DESTINATION_BTN = "trip_select_destination_btn"
    const val TRIP_PLAN_DESTINATION_BTN = "trip_plan_destination_btn"
    const val TRIP_FLEET_EDIT_BTN = "trip_fleet_edit_btn"
    const val ALERT_ABORT_TRIP_TTL = "alert_abort_trip_ttl"
    const val ALERT_ABORT_TRIP_MSG = "alert_abort_trip_msg"
    const val ALERT_TRIP_ABORT_CONFIRM_BTN = "alert_trip_abort_confirm_btn"
    const val ALERT_TRIP_ABORT_CANCEL_BTN = "alert_trip_abort_cancel_btn"
    const val TRIP_RETRY_AGAIN = "trip_retry_again"
    const val DESTINATION_EXTERNAL_ADDRESS_LBL = "destination_external_address_lbl"
    const val DESTINATION_LBL = "destination_lbl"
    const val DESTINATION_PRIORITY_COUNTER_LBL = "destination_priority_counter_lbl"
    const val DESTINATION_TODAY_COUNTER_LBL = "destination_today_counter_lbl"
    const val DESTINATION_LATE_COUNTER_LBL = "destination_late_counter_lbl"
    const val DESTINATION_NEXT_COUNTER_LBL = "destination_next_counter_lbl"
    const val DESTINATION_SERIAL_COUNTER_LBL = "destination_serial_counter_lbl"
    //WAITING_DESTINATION
    const val PLACEHOLDER_TRIP_WAITING_DESTINATION_TTL_LBL = "placeholder_trip_waiting_destination_ttl_lbl"
    const val PLACEHOLDER_TRIP_WAITING_DESTINATION_SUB_TTL_LBL = "placeholder_trip_waiting_destination_sub_ttl_lbl"
    const val TRIP_WAITING_DESTINATION_LBL = "trip_waiting_destination_lbl"
    const val TRIP_TO_TRANSFER_LBL = "trip_to_transfer_lbl"
    //TRANSIT
    const val TRIP_CALL_LBL = "trip_call_lbl"
    const val TRIP_MAP_LBL = "trip_map_lbl"
    const val TRIP_ON_SITE_LBL = "trip_on_site_lbl"
    const val TRIP_TO_ON_SITE_BTN = "trip_to_on_site_btn"
    const val TRIP_TRANSIT_LBL = "trip_transit_lbl"
    //TRANSFER
    const val PLACEHOLDER_TRIP_TRANSFER_TTL_LBL = "placeholder_trip_transfer_ttl_lbl"
    const val PLACEHOLDER_TRIP_TRANSFER_SUB_TTL_LBL = "placeholder_trip_transfer_sub_ttl_lbl"
    const val TRIP_TRANSFER_STATUS_LBL = "trip_transfer_status_lbl"
    const val TRIP_TO_OVER_NIGHT_LBL = "trip_to_over_night_lbl"
    const val TRIP_TO_END_LBL = "trip_to_end_lbl"
    //OVER NIGHT
    const val TRIP_OVER_NIGHT_LBL = "trip_over_night_lbl"
    const val PLACEHOLDER_TRIP_OVER_NIGHT_TTL = "placeholder_trip_over_night_ttl"
    const val PLACEHOLDER_TRIP_OVER_NIGHT_SUB_TTL = "placeholder_trip_over_night_sub_ttl"
    const val TRIP_TO_END_OVER_NIGHT_LBL = "trip_to_end_over_night_lbl"
    const val TRIP_RETURN_TO_TRANSIT_LBL = "trip_return_to_transit_lbl"
    const val TRIP_NEXT_DESTINATION_LBL = "trip_next_destination_lbl"
    const val ALERT_NO_NAVIGATION_APP_FOUND_TTL = "alert_no_navigation_app_found_ttl"
    const val ALERT_NO_NAVIGATION_APP_FOUND_MSG = "alert_no_navigation_app_found_msg"
    const val ALERT_NO_CONTACT_APP_FOUND_TTL = "alert_no_contact_app_found_ttl"
    const val ALERT_NO_CONTACT_APP_FOUND_MSG = "alert_no_contact_app_found_msg"
    //ON_SITE
    const val TRIP_DEPARTED_LBL = "trip_departed_lbl"
    const val TRIP_DESTINATION_ARRIVED_DATE_LBL = "trip_destination_arrived_date_lbl"
    const val TRIP_DESTINATION_SEARCH_SERIAL_LBL = "trip_destination_search_serial_lbl"
    const val TRIP_DESTINATION_MY_TICKETS_LBL= "trip_destination_my_tickets_lbl"
    const val TRIP_ON_SITE_ODOMETER_WARNING= "trip_on_site_odometer_warning"
    const val TRIP_ON_SITE_EXECUTION_LBL = "trip_on_site_execution_lbl"
    const val TRIP_ACTION_FORM_OS_BTN = "trip_action_form_os_btn"
    const val TRIP_SITE_TICKETS_BTN = "trip_site_tickets_btn"
    const val TRIP_DESTINATION_TICKETS_BTN = "trip_destination_tickets_btn"
    const val TRIP_ACTION_TICKET_BTN = "trip_action_ticket_btn"
    //TRIP WARNING
    const val TRIP_WARNING_DEPARTED_FROM_ORIGIN_TTL  = "trip_warning_departed_from_origin_ttl"
    const val TRIP_WARNING_DEPARTED_FROM_ORIGIN_MSG  = "trip_warning_departed_from_origin_msg"
    const val TRIP_WARNING_ARRIVED_TO_SITE_TTL  = "trip_warning_arrived_to_site_ttl"
    const val TRIP_WARNING_ARRIVED_TO_SITE_MSG  = "trip_warning_arrived_to_site_msg"
    const val TRIP_WARNING_DEPARTED_FROM_SITE_TTL  = "trip_warning_departed_from_site_ttl"
    const val TRIP_WARNING_DEPARTED_FROM_SITE_MSG  = "trip_warning_departed_from_site_msg"
    const val TRIP_WARNING_WAITING_DESTINATION_TTL  = "trip_warning_waiting_destination_ttl"
    const val TRIP_WARNING_WAITING_DESTINATION_MSG  = "trip_warning_waiting_destination_msg"
    //PDF ERROR
    const val ALERT_STARTING_PDF_NOT_SUPPORTED_TTL  = "alert_starting_pdf_not_supported_ttl"
    const val ALERT_STARTING_PDF_NOT_SUPPORTED_MSG  = "alert_starting_pdf_not_supported_msg"
    const val ALERT_PDF_NOT_FOUND_TTL  = "alert_pdf_not_found_ttl"
    const val ALERT_PDF_NOT_FOUND_MSG  = "alert_pdf_not_found_msg"
    const val ALERT_POSITION_NOT_FOUND_TTL  = "alert_position_not_found_ttl"
    const val ALERT_POSITION_NOT_FOUND_MSG  = "alert_position_not_found_msg"
}