package com.namoadigital.prj001.ui.act094.destination.domain.destination_availables

import android.content.Context
import com.google.gson.annotations.SerializedName
import com.namoadigital.prj001.util.ToolBox_Inf

data class DestinationAvailables(
    @SerializedName("destinationType") val destinationType: String? = null,
    @SerializedName("siteCode") val siteCode: Int? = null,
    @SerializedName("siteDesc") val siteDesc: String? = null,
    @SerializedName("ticketPrefix") val ticketPrefix: Int? = null,
    @SerializedName("ticketCode") val ticketCode: Int? = null,
    @SerializedName("serialId") val serialId: String? = null,
    @SerializedName("address") val address: Int? = null,
    @SerializedName("countryId") val countryId: String? = null,
    @SerializedName("state") val state: String? = null,
    @SerializedName("city") val city: String? = null,
    @SerializedName("district") val district: String? = null,
    @SerializedName("street") val street: String? = null,
    @SerializedName("streetnumber") val streetnumber: String? = null,
    @SerializedName("complement") val complement: String? = null,
    @SerializedName("zipcode") val zipcode: String? = null,
    @SerializedName("plus_code") val plusCode: String? = null,
    @SerializedName("latitude") val lat: Double? = null,
    @SerializedName("longitude") val lon: Double? = null,
    @SerializedName("contact") val contactName: String? = null,
    @SerializedName("phone") val contactPhone: String? = null,
    @SerializedName("siteMainUser") val siteMainUser: Int? = null,
    @SerializedName("regionCode") val regionCode: Int? = null,
    @SerializedName("regionDesc") val regionDesc: String? = null,
    @SerializedName("minDate") val minDate: String? = null,
    @SerializedName("priorityCnt") val priorityCnt: Int? = null,
    @SerializedName("todayCnt") val todayCnt: Int? = null,
    @SerializedName("lateCnt") val lateCnt: Int? = null,
    @SerializedName("nextCnt") val nextCnt: Int? = null,
    @SerializedName("serialCnt") val serialCnt: Int? = null,
) {


    fun formatToAddress(): String {
        val builder = StringBuilder()

        if (!street.isNullOrEmpty()) builder.append(street)
        if (!streetnumber.isNullOrEmpty()) builder.append(", $streetnumber")
        if (!complement.isNullOrEmpty()) builder.append(" - $complement")
        if (!district.isNullOrEmpty()) builder.append(" - $district")
        if (!city.isNullOrEmpty()) builder.append(", $city")
        if (!state.isNullOrEmpty()) builder.append(" - $state")
        if (!zipcode.isNullOrEmpty()) builder.append(", $zipcode")

        return builder.toString()
    }

    fun getAllFieldForFilter(context: Context) =
        listOf(
            serialId,
            siteDesc,
            regionDesc,
            street,
            streetnumber,
            complement,
            district,
            city,
            state,
            zipcode,
            ToolBox_Inf.millisecondsToString(
                ToolBox_Inf.dateToMilliseconds(minDate),
                ToolBox_Inf.nlsDateFormat(context)
            ),
        ).joinToString("|")

//    companion object EXAMPLE {
//
//        val list = """
//           [
//            {
//                "destinationType": "TICKET",
//                "siteCode": 31,
//                "siteDesc": "Barueri",
//                "ticketPrefix": 2023,
//                "ticketCode": 1828,
//                "serialId": "20220901_03",
//                "address": 1,
//                "countryId": "BRA",
//                "state": "SP",
//                "city": "Campinas",
//                "district": "Jardim Santa Monica",
//                "street": "Avenida Comendador Aladino Selmi",
//                "num": null,
//                "complement": "5 Pista Norte, Km 140",
//                "zipCode": "13082902",
//                "plusCode": "5W32+2Q",
//                "lat": null,
//                "lon": null,
//                "contactName": "José da Silva",
//                "contactPhone": "1143149045",
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": "2023-09-29 13:00:00 -03:00",
//                "priorityCnt": 0,
//                "todayCnt": 0,
//                "lateCnt": 1,
//                "preventiveCnt": 0,
//                "serialCnt": 1,
//                "cnt": 1
//            },
//            {
//                "destinationType": "TICKET",
//                "siteCode": 31,
//                "siteDesc": "Barueri",
//                "ticketPrefix": 2023,
//                "ticketCode": 1831,
//                "serialId": "20220901_03",
//                "address": 1,
//                "countryId": "BRA",
//                "state": "SP",
//                "city": "Osasco",
//                "district": "Jardim Munhoz Junior",
//                "street": "Rua Vinte e Um",
//                "num": "21",
//                "complement": "casa",
//                "zipCode": "06030460",
//                "plusCode": "588MF5RR+9C",
//                "lat": -23.5093691,
//                "lon": -46.8087754,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": "2023-10-04 08:00:00 -03:00",
//                "priorityCnt": 1,
//                "todayCnt": 0,
//                "lateCnt": 0,
//                "preventiveCnt": 0,
//                "serialCnt": 1,
//                "cnt": 1
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 3,
//                "siteDesc": "Campinas",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 1,
//                "countryId": "BRA",
//                "state": "SP",
//                "city": "São Caetano do Sul",
//                "district": "Cerâmica",
//                "street": "Alameda Terracota",
//                "num": "185",
//                "complement": "Sala 815",
//                "zipCode": "09531-190",
//                "plusCode": "588M9CG9+6M",
//                "lat": -23.6240509,
//                "lon": -46.5806709,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 1,
//                "regionDesc": "Campinas e região",
//                "minDate": "2023-05-16 08:00:00 -03:00",
//                "priorityCnt": 1,
//                "todayCnt": 0,
//                "lateCnt": 1,
//                "preventiveCnt": 1,
//                "serialCnt": 1,
//                "cnt": 1
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 4,
//                "siteDesc": "Jundiaí",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 1,
//                "regionDesc": "Campinas e região",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 39,
//                "siteDesc": "Novo",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": null,
//                "regionDesc": null,
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 14,
//                "siteDesc": "Novo Site",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 1,
//                "countryId": "BRA",
//                "state": "SP",
//                "city": "São Paulo",
//                "district": "Alto da Boa Vista",
//                "street": "Rua Bela Vista",
//                "num": "105",
//                "complement": null,
//                "zipCode": "04709-000",
//                "plusCode": "588M9886+43",
//                "lat": -23.6347777,
//                "lon": -46.6899009,
//                "contactName": "Tio Sam",
//                "contactPhone": "6060606060 / 2222222",
//                "siteMainUser": null,
//                "regionCode": null,
//                "regionDesc": null,
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 22,
//                "siteDesc": "Novo Site Novo",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 6,
//                "siteDesc": "Prédio Teste 6A",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": null,
//                "regionDesc": null,
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 1,
//                "siteDesc": "São Caetano do Sul",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 1,
//                "countryId": "BRA",
//                "state": "SP",
//                "city": "São Caetano do Sul",
//                "district": "Cerâmica",
//                "street": "Alameda Terracota",
//                "num": "187",
//                "complement": "Sala 815",
//                "zipCode": "09531-190",
//                "plusCode": "588M9CG9+8I",
//                "lat": -23.6241721,
//                "lon": -46.5809609,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": 3,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 2,
//                "siteDesc": "São Paulo",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 42,
//                "siteDesc": "site",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 1,
//                "countryId": "BRA",
//                "state": "SP",
//                "city": "São Paulo",
//                "district": "Parque Sao Rafael",
//                "street": "Rua Francisco Marques",
//                "num": "12",
//                "complement": null,
//                "zipCode": "08311150",
//                "plusCode": "588M9G8J+XW",
//                "lat": -23.6326164,
//                "lon": -46.4675974,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 30,
//                "siteDesc": "Site upload",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 1,
//                "countryId": "DEU",
//                "state": "SL",
//                "city": "Saarbrücken",
//                "district": null,
//                "street": "Am Halberg",
//                "num": "6-7",
//                "complement": null,
//                "zipCode": "66121",
//                "plusCode": "8FX962FR+VV",
//                "lat": 49.2248102,
//                "lon": 7.0424678,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 20,
//                "siteDesc": "so-planning-site-desc-019",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 41,
//                "siteDesc": "teste",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 1,
//                "countryId": "BRA",
//                "state": "SP",
//                "city": "São Paulo",
//                "district": "Parque Sao Rafael",
//                "street": "Rua Francisco Marques",
//                "num": null,
//                "complement": null,
//                "zipCode": "08311150",
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 34,
//                "siteDesc": "teste create site kanban 001",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 35,
//                "siteDesc": "teste create site kanban 002",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 36,
//                "siteDesc": "teste create site kanban 003",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 37,
//                "siteDesc": "teste create site kanban 004",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": 10100,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 38,
//                "siteDesc": "teste create site kanban 005",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": 10100,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 26,
//                "siteDesc": "Teste Planejamento II",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 4,
//                "regionDesc": "ABCD Paulista",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 32,
//                "siteDesc": "Teste WG",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": 2,
//                "regionDesc": "REGIÃO 2",
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 40,
//                "siteDesc": "Upload #1",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": null,
//                "regionDesc": null,
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            },
//            {
//                "destinationType": "SITE",
//                "siteCode": 33,
//                "siteDesc": "X",
//                "ticketPrefix": null,
//                "ticketCode": null,
//                "serialId": null,
//                "address": 0,
//                "countryId": null,
//                "state": null,
//                "city": null,
//                "district": null,
//                "street": null,
//                "num": null,
//                "complement": null,
//                "zipCode": null,
//                "plusCode": null,
//                "lat": null,
//                "lon": null,
//                "contactName": null,
//                "contactPhone": null,
//                "siteMainUser": null,
//                "regionCode": null,
//                "regionDesc": null,
//                "minDate": null,
//                "priorityCnt": null,
//                "todayCnt": null,
//                "lateCnt": null,
//                "preventiveCnt": null,
//                "serialCnt": null,
//                "cnt": null
//            }
//        ]
//        """.trimIndent()
//    }
}